AWSTemplateFormatVersion: '2010-09-09'
Description: Create a User on the User Table
Parameters:
  RestApi:
    Description: Name of the RestAPI
    Type: String
  ResourceId:
    Description: ID of the Resource
    Type: String
  Stage:
    Description: Stage
    Type: String
Resources:
  UserCreateApi:
    Type: AWS::ApiGateway::Method
    DependsOn:
    - UserCreateLambda
    Properties:
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri: !Sub
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
          - lambdaArn: !GetAtt "UserCreateLambda.Arn"
      RestApiId: !Ref RestApi
      ResourceId: !Ref ResourceId

  UserCreateLambda:
    Type: AWS::Lambda::Function
    DependsOn:
    - UserCreateIamRole
    Properties:
      Code: ./
      Description: Function to Create User
      FunctionName: UserCreate
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt "UserCreateIamRole.Arn"
      Runtime: nodejs8.10
      Timeout: 60
      Environment:
        Variables:
          USER_TABLE: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Stage}-UserTable"
  UserCreateIamRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Effect: "Allow"
                Resource: '*'
              - Action:
                  - "ec2:CreateNetworkInterface"
                  - "ec2:DescribeNetworkInterfaces"
                  - "ec2:DeleteNetworkInterface"
                Effect: "Allow"
                Resource: '*'
              - Action:
                  - "dynamodb:PutItem"
                Effect: "Allow"
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Stage}-UserTable"
          PolicyName: "UserCreateIamRole"
  UserCreateApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt "UserCreateLambda.Arn"
      Principal: "apigateway.amazonaws.com"
